### PR TITLE
Config with default template

### PR DESCRIPTION
**Pull request by gforcada**
Using https://github.com/plone/meta/pull/51

### CODE REVIEW

**Review by mauritsvanrees — APPROVED** [review]
Thanks!

**Comment by mauritsvanrees** [comment]
Can be merged when green.

@jenkins-plone-org please run jobs

**Comment by gforcada** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
All four Jenkins runs fail at the same test in [`plone.app.event`](https://github.com/plone/plone.app.event/blob/4.0.0/plone/app/event/tests/test_portlet_calendar.py#L183-L197).  But a few core jobs fail with the same error.  Since the test handles with dates and a calendar portlet, it may fail at the end of the month.  Maybe especially at the end of February.  And it may depend on timezones.

I restarted the failing core jobs.  I will start one job for this PR (3.10).  If that passes, I am happy for this to be merged.

**Comment by mauritsvanrees** [comment]
The one Jenkins PR job I started again, passes now.  I merge.  Thanks!

**Pull request merged**
